<?php

/**
 * @file
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\diff\Routing\DiffRouteProvider;

/**
 * Implements hook_entity_type_alter().
 */
function diff_test_entity_type_alter(array &$entity_types): void {
  $entity_type_ids = ['entity_test_rev', 'entity_test_revlog'];
  foreach ($entity_type_ids as $entity_type_id) {
    if (!isset($entity_types[$entity_type_id])) {
      continue;
    }
    /** @var \Drupal\Core\Entity\EntityType $entity_type */
    $entity_type = $entity_types[$entity_type_id];
    $handlers = $entity_type->get('handlers');
    $handlers['route_provider']['html_diff'] = DiffRouteProvider::class;
    $entity_type->set('handlers', $handlers);
    $entity_type->setLinkTemplate('revisions-diff', \sprintf('/%s/{%s}/revision/{left_revision}/{right_revision}', $entity_type_id, $entity_type_id));
  }
}

/**
 * Implements hook_entity_field_access().
 */
function diff_test_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, ?FieldItemListInterface $items = NULL): AccessResult {
  if ($field_definition->getName() == 'field_diff_deny_access') {
    return AccessResult::forbidden();
  }
  return AccessResult::allowed();
}
